kind: AnalysisTemplate
apiVersion: argoproj.io/v1alpha1
metadata:
  name: security-check
  namespace: demo
spec:
  args:
    - name: image-digest
    - name: namespace
    - name: pod-hash
  metrics:
    - name: security-check
      interval: 10s
      count: 3
      successCondition: "result == 'pass'"
      failureCondition: "result == 'fail'"
      provider:
        web:
          url: "http://analysis-runner.demo.svc.cluster.local:8081/check"
          method: POST
          body: '{"image_digest": "{{args.image-digest}}", "namespace": "{{args.namespace}}", "pod_template_hash": "{{args.pod-hash}}"}'
          jsonPath: "{$.overall_status}"
