kind: Rollout
apiVersion: argoproj.io/v1alpha1
metadata:
  name: target-app
  namespace: demo
spec:
  replicas: 5
  strategy:
    canary:
      steps:
        - setWeight: 20
        - analysis:
            templates:
              - templateName: security-check
            args:
              - name: image-digest
                value: "rutujkoli/target-app@sha256:9a66d59caca51a34cdfddc70107da162e2e9e0fb8425ff29264536c1ba52dafd"
              - name: namespace
                valueFrom:
                  fieldRef:
                    fieldPath: metadata.namespace
              - name: pod-hash
                valueFrom:
                  podTemplateHashValue: Latest
        - setWeight: 50
        - pause: {duration: 30s}
        - setWeight: 100
  selector:
    matchLabels:
      app: target-app
  template:
    metadata:
      labels:
        app: target-app
    spec:
      containers:
        - name: target-app
          image: rutujkoli/target-app@sha256:d35b16f5b6d535e81be4e219c385a034c34c569c9d005f08ea2802857f192ef2
          ports:
          ports:
          -  containerPort: 8080
      
